[build]
  publish = "frontend/build"  # Path to the frontend build folder
  command = "cd frontend && npm run build"  # Build command for frontend

[dev]
  # Command to start the frontend React dev server
  command = "cd frontend && npm start"
  port = 3000  # Port for React app (frontend)
  targetPort = 8888  # Port for backend serverless functions
  functions = "backend/functions"  # Path to the backend functions directory
